apiVersion: apps/v1beta2 # for versions 1.9.0 use apps/v1
kind: Deployment
metadata:
  name: nginx-react-deployment
  labels:
    app: nginx-react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-react
  template:
    metadata:
      labels:
        app: nginx-react
    spec:
      containers:
      - name: nginx-react
        image: ziaukhan/nginx-react:step03
        ports:
        - containerPort: 80