apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-react
  name: nginx-react-loadbalancer
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-react
  sessionAffinity: None
  type: LoadBalancer